In [8]:
import numpy as np

In [9]:
x = np.random.rand(10)

In [10]:
n_output = 2

In [64]:
x

array([0.86596159, 0.17197256, 0.03672085, 0.58130495, 0.88763159,
       0.39529345, 0.84204086, 0.33319103, 0.34652514, 0.41107535])

In [65]:
w = np.random.rand(x.shape[0], n_output)

In [66]:
w

array([[0.7942668 , 0.44719953],
       [0.23833256, 0.71707063],
       [0.26346931, 0.19256594],
       [0.07869952, 0.74332358],
       [0.38370341, 0.60033811],
       [0.36533611, 0.80963661],
       [0.58465492, 0.81158728],
       [0.9225543 , 0.9029359 ],
       [0.46366596, 0.52035996],
       [0.55240232, 0.28676725]])

In [67]:
b = np.random.rand(n_output)

In [68]:
y = x @ w + b

In [69]:
y

array([3.07911038, 3.15077745])

In [70]:
def forward(x, w, b):
    return x @ w + b

In [103]:
def backward(dy, x, w, b):
    return w @ dy, np.expand_dims(x, 1) @ np.expand_dims(dy, 0), dy*1

In [104]:
def forward_sigmoid(x):
    return 1/(1 + np.exp(-x)) 

In [105]:
def backward_sigmoid(dy, x):
    return dy * (forward_sigmoid(x) * (1 - forward_sigmoid(x)))

In [106]:
out1 = forward(x, w, b)
out1

array([3.07911038, 3.15077745])

In [107]:
out2 = forward_sigmoid(out1)
out2

array([0.9560228 , 0.95893934])

In [108]:
d_out1 = backward_sigmoid(dy=1, x=out1)

In [109]:
dx, dw, db = backward(dy=d_out1, x=x, w=w, b=b)

In [113]:
out2

array([0.9560228 , 0.95893934])

In [114]:
target = np.array([0.5, 0.1])