In [1]:
import numpy as np

In [2]:
x = np.random.rand(10)

In [3]:
n_output = 2

In [4]:
x

array([0.62294096, 0.25759515, 0.10243237, 0.38599062, 0.2688156 ,
       0.94119191, 0.59682842, 0.33307421, 0.55770885, 0.81527311])

In [5]:
w = np.random.rand(x.shape[0], n_output)

In [6]:
w

array([[0.89939455, 0.12447209],
       [0.53156566, 0.51102459],
       [0.18864994, 0.26378664],
       [0.21111234, 0.9244762 ],
       [0.3074879 , 0.81250894],
       [0.8934322 , 0.35066824],
       [0.81159692, 0.27980429],
       [0.14398965, 0.64370996],
       [0.60308201, 0.33370867],
       [0.71402743, 0.74287655]])

In [7]:
b = np.random.rand(n_output)

In [8]:
y = x @ w + b

In [9]:
y

array([3.67089177, 2.3702962 ])

In [10]:
var = {
    'x @ w + b' : []
}

In [11]:
class LinearFunction(object):
    def __init__(self):
        self.c = {}

    def forward(self, x, w, b):
        self.c['x'] = x
        self.c['w'] = w
        self.c['b'] = b
        return x @ w + b
    
    def backward(self, dy):        
        return self.c['w'] @ dy, np.expand_dims(self.c['x'], 1) @ np.expand_dims(dy, 0), dy*1

In [12]:
class SigmoidFunction(object):
    def __init__(self):
        self.c = {}
        
    def forward(self, x):
        self.c['x'] = x
        return self.sigmoid(x)
    
    def sigmoid(self, x):
        return 1/(1 + np.exp(-x)) 
    
    def backward(self, dy):
        return dy * (self.sigmoid(self.c['x']) * (1 - self.sigmoid(self.c['x'])))

In [13]:
f = LinearFunction()
out1 = f.forward(x, w, b)
out1

array([3.67089177, 2.3702962 ])

In [14]:
s = SigmoidFunction()
out2 = s.forward(out1)
out2

array([0.97517805, 0.91453401])

In [15]:
d_out1 = s.backward(dy=1)

In [16]:
dx, dw, db = f.backward(dy=d_out1)

In [17]:
out2

array([0.97517805, 0.91453401])

In [18]:
target = np.array([0.5, 0.1])

In [30]:

class Network(object):
    def __init__(self, input_size, output_size):
        self.f = LinearFunction()
        self.s = SigmoidFunction()
        
        self.w = np.random.normal(loc=1, scale=1, size=(input_size, output_size))
        self.b = np.zeros(output_size)
    
    def forward(self, x):
        y1 = self.f.forward(x, self.w, self.b)
        y2 = self.s.forward(y1)
        return y2

    def backward(self, grad):
        dy2_dy1 = self.s.backward(dy=grad)
        return f.backward(dy=dy2_dy1)

class LossL1Function(object):
    def __init__(self):
        self.c = {}
        
    def forward(self, y, y_target):
        self.c['y'] = y
        self.c['y_target'] = y_target
        d = y_target - y
        self.c['d'] = d
        return np.mean(np.abs(d))
    
    def backward(self):
        weight = 1 / self.c['d'].shape[0]
        dl_dd = weight * ((self.c['d'] > 0) * 1.0 + (self.c['d'] < 0) * -1.0)
        dd_dy = dl_dd * -1
        
        return dd_dy
    
def step(n, loss_object, x, y_target, lr=0.01):
    y = n.forward(x)
    
    loss = loss_object.forward(y, y_target)
    dl_dy = loss_object.backward()
    
    _, dw, db = n.backward(grad=dl_dy)
    
    n.w = n.w - dw * lr
    n.b = n.b - db * lr
    return y, loss

In [31]:
def train():
    n = Network(input_size=10, output_size=2)
    loss = LossL1Function()
    
    x = np.random.randn(10, )
    target = np.array([0.5, 0.1])
    lr = 0.1
    for i in range(10000):
        out, lss = step(n, loss, x, target, lr=lr)
        if i % 100 == 0:
            print(out)
            
        if i % 1000 == 0:
            lr = lr - 0.001

train()

[0.42201339 0.10540927]
[0.50238675 0.10024339]
[0.50238968 0.10014018]
[0.50239263 0.10003724]
[0.5023956  0.09993435]
[0.50239858 0.0998316 ]
[0.50240158 0.0997291 ]
[0.50240459 0.09962686]
[0.50240763 0.09952487]
[0.50241067 0.10038343]
[0.50241374 0.10027988]
[0.50237916 0.10017377]
[0.5023821 0.1000728]
[0.50238505 0.09997201]
[0.50238801 0.09987123]
[0.50239099 0.0997707 ]
[0.50239399 0.09967041]
[0.50239701 0.09957036]
[0.50240004 0.10042201]
[0.50240309 0.10032044]
[0.50240615 0.10021912]
[0.50237157 0.10011521]
[0.50237451 0.10001643]
[0.50237746 0.09991765]
[0.50238042 0.09981904]
[0.5023834  0.09972067]
[0.5023864  0.09962254]
[0.50238941 0.10046737]
[0.50239244 0.10036775]
[0.50239548 0.10026837]
[0.50239854 0.10016923]
[0.50236396 0.10006746]
[0.5023669  0.09997073]
[0.50236984 0.09987403]
[0.5023728  0.09977755]
[0.50237578 0.09968129]
[0.50237877 0.09958526]
[0.50238178 0.10042167]
[0.50238481 0.1003242 ]
[0.50238784 0.10022696]
[0.5023909  0.10012994]
[0.50235632 0.1000