In [1]:
import numpy as np

In [2]:
x = np.random.rand(10)

In [3]:
n_output = 2

In [4]:
x

array([0.68029396, 0.32840694, 0.50191594, 0.63963333, 0.78756669,
       0.67858827, 0.38287083, 0.84975711, 0.96254636, 0.09100671])

In [5]:
w = np.random.rand(x.shape[0], n_output)

In [6]:
w

array([[0.19244329, 0.73747582],
       [0.21330963, 0.13864845],
       [0.53277022, 0.36644369],
       [0.50962357, 0.35139524],
       [0.86735692, 0.37366167],
       [0.25783492, 0.71356104],
       [0.29722212, 0.88140445],
       [0.34894402, 0.66695864],
       [0.84775568, 0.75580885],
       [0.16904583, 0.98275015]])

In [7]:
b = np.random.rand(n_output)

In [8]:
y = x @ w + b

In [9]:
y

array([3.39971275, 3.92239271])

In [10]:
def forward(x, w, b):
    return x @ w + b

In [11]:
def backward(dy, x, w, b):    
    return w @ dy, np.expand_dims(x, 1) @ np.expand_dims(dy, 0), dy*1

In [12]:
def forward_sigmoid(x):
    return 1/(1 + np.exp(-x)) 

In [13]:
def backward_sigmoid(dy, x):
    return dy * (forward_sigmoid(x) * (1 - forward_sigmoid(x)))

In [14]:
out1 = forward(x, w, b)
out1

array([3.39971275, 3.92239271])

In [15]:
out2 = forward_sigmoid(out1)
out2

array([0.96769556, 0.98059051])

In [16]:
d_out1 = backward_sigmoid(dy=1, x=out1)

In [17]:
dx, dw, db = backward(dy=d_out1, x=x, w=w, b=b)

In [18]:
out2

array([0.96769556, 0.98059051])

In [19]:
target = np.array([0.5, 0.1])

In [20]:
def step(x, w, b, y_target, lr=0.01):
    y1 = forward(x, w, b)    
    y2 = forward_sigmoid(y1)
    
    d = y_target - y2
    
    loss = np.mean(np.abs(d))
    
    dl_dd = 0.5*((d > 0) * 1.0 + (d < 0) * -1.0)
    dd_dy2 = dl_dd * -1
    
    dy2_dy1 = backward_sigmoid(dy=dd_dy2, x=y1)
    dy1_dx, dy1_dw, dy1_db = backward(dy=dy2_dy1, x=x, w=w, b=b)
    
    w = w - dy1_dw * lr
    b = b - dy1_db * lr
    return w, b, y2, loss

In [31]:
def train():
    x = np.random.randn(10, )
    w = np.random.normal(loc=1, scale=1, size=(x.shape[0], n_output)) #np.random.randn(x.shape[0], n_output)
    b = np.zeros(n_output)
    target = np.array([0.5, 0.1])
    lr = 0.1
    for i in range(10000+1):
        
        w, b, out, lss = step(x, w, b, target, lr=lr)
        if i % 500 == 0:
            print(out)
        if i % 1000 == 0:
            lr = lr - 0.001
    
train()

[0.00666445 0.04092832]
[0.03413336 0.09937262]
[0.50591453 0.09843542]
[0.50459133 0.10158605]
[0.50272011 0.10071157]
[0.49999703 0.09992983]
[0.49999943 0.09917497]
[0.49999551 0.09854615]
[0.49999686 0.10179995]
[0.49999908 0.10119315]
[0.50000002 0.10061596]
[0.49999528 0.1001179 ]
[0.49999619 0.09964169]
[0.50000631 0.09927917]
[0.50000636 0.09890045]
[0.49999043 0.09863036]
[0.49998859 0.0983431 ]
[0.50000887 0.10186231]
[0.5000104  0.10164487]
[0.50001058 0.10149475]
[0.49998873 0.10136658]
