In [1]:
import numpy as np

In [2]:
x = np.random.rand(10)

In [3]:
n_output = 2

In [4]:
x

array([0.98595218, 0.82077203, 0.94843808, 0.19541009, 0.64266266,
       0.60735443, 0.66697532, 0.63058731, 0.39327905, 0.76840853])

In [5]:
w = np.random.rand(x.shape[0], n_output)

In [6]:
w

array([[0.11414765, 0.50679107],
       [0.94431806, 0.66475222],
       [0.06927808, 0.90356025],
       [0.7687316 , 0.35793945],
       [0.94722731, 0.11883859],
       [0.0441511 , 0.56223291],
       [0.37764124, 0.30053133],
       [0.08177501, 0.91693764],
       [0.43644913, 0.87653653],
       [0.62347735, 0.72032927]])

In [7]:
b = np.random.rand(n_output)

In [8]:
y = x @ w + b

In [9]:
y

array([3.30379119, 4.40446916])

In [10]:
def forward(x, w, b):
    return x @ w + b

In [11]:
def backward(dy, x, w, b):    
    return w @ dy, np.expand_dims(x, 1) @ np.expand_dims(dy, 0), dy*1

In [12]:
def forward_sigmoid(x):
    return 1/(1 + np.exp(-x)) 

In [13]:
def backward_sigmoid(dy, x):
    return dy * (forward_sigmoid(x) * (1 - forward_sigmoid(x)))

In [14]:
out1 = forward(x, w, b)
out1

array([3.30379119, 4.40446916])

In [15]:
out2 = forward_sigmoid(out1)
out2

array([0.96455864, 0.98792499])

In [16]:
d_out1 = backward_sigmoid(dy=1, x=out1)

In [17]:
dx, dw, db = backward(dy=d_out1, x=x, w=w, b=b)

In [18]:
out2

array([0.96455864, 0.98792499])

In [19]:
target = np.array([0.5, 0.1])

In [58]:
def step(x, w, b, y_target, lr=0.01):
    y1 = forward(x, w, b)    
    y2 = forward_sigmoid(y1)
    
    
    w = y_target - y2
    loss = np.mean(np.abs(w))
    
    dl_dw = 0.5*((w > 0) * 1.0 + (w < 0) * -1.0)
    dw_dy2 = dl_dw * -1
    
    dy2_dy1 = backward_sigmoid(dy=dw_dy2, x=y1)
    dy1_dx, dy1_dw, dy1_db = backward(dy=dy2_dy1, x=x, w=w, b=b)
    
    w = w - dy1_dw * lr
    b = b - dy1_db * lr
    return w, b, y2, loss

In [65]:
def train():
    x = np.random.randn(10, )
    w = np.random.normal(loc=1, scale=1, size=(x.shape[0], n_output)) #np.random.randn(x.shape[0], n_output)
    b = np.zeros(n_output)
    target = np.array([0.5, 0.1])
    lr = 0.1
    for i in range(10000):
        
        w, b, out, lss = step(x, w, b, target, lr=lr)
        if i % 100 == 0:
            print(out)
            lr = lr - 0.001

train()

[0.00714781 0.00645259]
[0.49663611 0.27158541]
[0.4969813  0.13273347]
[0.49733009 0.1025944 ]
[0.49768232 0.1019929 ]
[0.49803778 0.10141158]
[0.49839631 0.10084966]
[0.49875769 0.1003064 ]
[0.49912173 0.09747969]
[0.49948821 0.10011015]
[0.49985693 0.0973624 ]
[0.51396828 0.09770588]
[0.51398585 0.1002739 ]
[0.51400337 0.09762247]
[0.51402075 0.10013777]
[0.51403787 0.09756112]
[0.51405461 0.10002435]
[0.51407089 0.10035505]
[0.51408658 0.09787163]
[0.51410158 0.10027295]
[0.51411578 0.09786094]
[0.51412909 0.10021111]
[0.5141414  0.09786909]
[0.5141526  0.10016845]
[0.51416261 0.09789517]
[0.51417131 0.10014398]
[0.51417863 0.09793831]
[0.51418447 0.10013674]
[0.51418873 0.09799762]
[0.49689656 0.10014579]
[0.49708757 0.09807225]
[0.49727813 0.1001702 ]
[0.49746817 0.09816138]
[0.49765764 0.10020905]
[0.49784646 0.09826415]
[0.49803457 0.10026146]
[0.49822192 0.09999706]
[0.49840845 0.09816466]
[0.4985941  0.10007671]
[0.49877881 0.09829712]
[0.49896254 0.10015847]
[0.49914524 0.09