In [123]:
import numpy as np

In [124]:
x = np.random.rand(10)

In [125]:
n_output = 2

In [126]:
x

array([0.39817966, 0.96731862, 0.34765035, 0.80118311, 0.9225874 ,
       0.24613924, 0.62362715, 0.77450788, 0.57295663, 0.29503775])

In [127]:
w = np.random.rand(x.shape[0], n_output)

In [128]:
w

array([[0.2217311 , 0.30185864],
       [0.71382226, 0.73878082],
       [0.64756463, 0.09654663],
       [0.74250479, 0.72942769],
       [0.68812371, 0.79230672],
       [0.93218787, 0.19546195],
       [0.39042237, 0.65062857],
       [0.67040109, 0.51221764],
       [0.30281206, 0.86936902],
       [0.6052326 , 0.65916643]])

In [129]:
b = np.random.rand(n_output)

In [130]:
y = x @ w + b

In [131]:
y

array([4.55315612, 4.28232724])

In [132]:
var = {
    'x @ w + b' : []
}

In [133]:
class LinearFunction(object):
    def __init__(self):
        self.c = {}

    def forward(self, x, w, b):
        self.c['x'] = x
        self.c['w'] = w
        self.c['b'] = b
        return x @ w + b
    
    def backward(self, dy):        
        return self.c['w'] @ dy, np.expand_dims(self.c['x'], 1) @ np.expand_dims(dy, 0), dy*1

In [134]:
class SigmoidFunction(object):
    def __init__(self):
        self.c = {}
        
    def forward(self, x):
        self.c['x'] = x
        return self.sigmoid(x)
    
    def sigmoid(self, x):
        return 1/(1 + np.exp(-x)) 
    
    def backward(self, dy):
        return dy * (self.sigmoid(self.c['x']) * (1 - self.sigmoid(self.c['x'])))

In [135]:
f = LinearFunction()
out1 = f.forward(x, w, b)
out1

array([4.55315612, 4.28232724])

In [136]:
s = SigmoidFunction()
out2 = s.forward(out1)
out2

array([0.9895759 , 0.98637765])

In [137]:
d_out1 = s.backward(dy=1)

In [138]:
dx, dw, db = f.backward(dy=d_out1)

In [139]:
out2

array([0.9895759 , 0.98637765])

In [140]:
target = np.array([0.5, 0.1])

In [141]:
def step(x, w, b, y_target, lr=0.01):
    f = LinearFunction()
    s = SigmoidFunction()
    
    y1 = f.forward(x, w, b)
    y2 = s.forward(y1)
    
    w = y_target - y2
    loss = np.mean(np.abs(w))
    
    dl_dw = 0.5*((w > 0) * 1.0 + (w < 0) * -1.0)
    dw_dy2 = dl_dw * -1
    
    dy2_dy1 = s.backward(dy=dw_dy2)
    dy1_dx, dy1_dw, dy1_db = f.backward(dy=dy2_dy1)
    
    w = w - dy1_dw * lr
    b = b - dy1_db * lr
    return w, b, y2, loss

In [142]:
def train():
    n_output = 2
    x = np.random.randn(10, )
    w = np.random.normal(loc=1, scale=1, size=(x.shape[0], n_output)) #np.random.randn(x.shape[0], n_output)
    b = np.zeros(n_output)
    target = np.array([0.5, 0.1])
    lr = 0.1
    for i in range(10000):
        
        w, b, out, lss = step(x, w, b, target, lr=lr)
        if i % 100 == 0:
            print(out)
            lr = lr - 0.001

train()

[0.66545025 0.95298605]
[0.47213026 0.24969714]
[0.47200921 0.13342619]
[0.47187333 0.1057443 ]
[0.47172253 0.10446275]
[0.47155678 0.10324186]
[0.47137609 0.10207789]
[0.47118049 0.10096742]
[0.47097008 0.09465783]
[0.47074499 0.09452385]
[0.4705054  0.10030873]
[0.47025154 0.10011613]
[0.46998368 0.09490215]
[0.46970214 0.09481111]
[0.46940729 0.09473077]
[0.46909953 0.10024925]
[0.46877932 0.10011398]
[0.46844716 0.0999898 ]
[0.46810358 0.09518383]
[0.46774918 0.09515199]
[0.46738457 0.09512941]
[0.46701041 0.10069692]
[0.46662739 0.1002602 ]
[0.46623624 0.10019542]
[0.46583771 0.10013988]
[0.502194   0.10009332]
[0.50139654 0.10005549]
[0.5005935  0.10002616]
[0.46996763 0.10000509]
[0.46974094 0.09999207]
[0.46951264 0.09999565]
[0.46928336 0.10000678]
[0.50234609 0.10001639]
[0.50170256 0.10003309]
[0.50105868 0.10005663]
[0.50041503 0.10008684]
[0.4732546  0.10012351]
[0.47316915 0.10016642]
[0.47308613 0.10021538]
[0.47300597 0.09620527]
[0.47292907 0.09632577]
[0.50177684 0.09